version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "jvrs"
      MYSQL_DATABASE: "DBSKADI"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network
  skadi-backend:
    image: skadi-backend:1.0
    ports:
      - "80:80"
    depends_on:
      - mysqlsrv
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: [ "dotnet", "backend.dll" ]

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
