// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.db;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(SKADIDBContext))]
    [Migration("20220115182631_Migrations")]
    partial class Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.model.Enterprise", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("stateregistration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Enterprise");
                });

            modelBuilder.Entity("backend.model.EnterpriseUser", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("idEnterprise")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("EnterpriseUsers");
                });

            modelBuilder.Entity("backend.model.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("backend.model.Enterprise", b =>
                {
                    b.OwnsOne("backend.model.NameEnterprise", "settings", b1 =>
                        {
                            b1.Property<string>("Enterpriseid")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("name")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("namefantasy")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("slug")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("Enterpriseid");

                            b1.ToTable("Enterprise");

                            b1.WithOwner()
                                .HasForeignKey("Enterpriseid");
                        });

                    b.Navigation("settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
